[package]
name = "nerf-this"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.15"
tokio = { version = "1.17.0", features = ["full"] }
colored = "2"